language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.2"
script: bundle exec rspec spec

notifications:
  slack:
    rooms:
      # Sending to liggat#notifications. Encrypted via: `travis encrypt "liggat:$SEMI_SECRET_TOKEN"`.
      secure: "BWnYsILnxl4vmGnGluSZ+lZgb6nbY1I4XNffXLeLOOgB93v1m/Y64nQTbbglPZCgl8nOEFa0vjGW0Uah5T94s0/bPE3jactBekiuc/fifHtR0SH6fH1T2p9tr7NCuDZ+n6CQywvdk+vHYNN+sE2AkGiEXjCJ33EmQzI972KyVmzukXrgloH167Gi0u7lL9Qfeg6yiPNLRk60r2ca/idKrCz9WB9rFkxnrNpyDmIUiYPlw4F9bUwo22fj7OIZayDxdk7nOIRE0gXUex5mXnLGzlPFeunLMRMaQ87SI+EZW8/w33s7jOwA3zs8g+ZX5FeV1buVLzRS+e8qbLKULWtXAgBT/lqRbqglV+lQwr9EBaTjfaltf9HDIyVNjGb/HSRIjkyAIVz2KsyKgVTfmJrnfy6zgEO2BMx9iHbhMxrysA8t0FZXTqrXzWnBsgaeSN1ClJDm6FkS4O/eyBycNtEq+m+wbPTSukgbuQIW4idJjGCYNJslTkCrGdqgixDW/Z7A3Qa08vK7AuKFenen8niq7dZ91Y6CxKTGbIvV9LRHzaPZvMjlZAJEQBT+dCBeoga87ax3U65OzDtNiUoEm8WPIa1IwLai5Dv5+CGISZv/ylWD19vMvxRjMTZC2z0zDjLDGsupw5ZrYXZwW3q3gQc51/gUfJlRvpAKIi9hQ083EvY="
    on_success: always
    on_failure: always
